#!/bin/sh

export IFS=' 	
'
syspath=$(command -p getconf PATH 2>/dev/null)
export PATH="${syspath:-/bin:/usr/bin}${PATH:+:$PATH}"

progname=INSTALL
usage="./$progname [-f]"
[ "X$0" = "X./$progname" ] || { echo "run ./$progname in its parent dir" >&2; exit 1; }

exclude(){
	# list files not to install
	grep -v '^\.git$
^LICENSE$
^README\.md$
^INSTALL$
.*\.swp$'
}

displayHelp(){
	cat <<EOF >&2
usage: $usage

option:
	-f	force to install dotfiles
EOF
}

fFlag=
while getopts fh opt; do
	case $opt in
	f)	fFlag=-f;;
	h)	displayHelp;exit 0;;
	?)	printf 'usage: %s\n' "$usage" >&2; exit 1;;
	esac
done


ls -A | exclude | xargs -I {} ln -s $fFlag $PWD/{} $HOME/{}
